name: Publish Release
on:
  push:
    tags:
      - '*'
env:
  bintray_user: ${{ secrets.bintray_user }}
  bintray_key: ${{ secrets.bintray_key }}

jobs:
#  bintray:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 8
#      - uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: bintrayUpload
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: remapJar
      - name: Remove dev jar
        run: rm ./build/libs/patchwork*/actions-dev.jar
      - name: Rename production jar
        run: mv ./build/libs/patchwork*/actions.jar ./build/libs/patchwork*/patchwork-api.jar
      - uses: actions/release-action@v1.4.0
        with:
          artifact: ./build/libs/patchwork*/patchwork-api.jar
          token: ${{ secrets.GITHUB_TOKEN }}
